package sa.elm.ob.hcm.util;

/**
 * Holds keys for all messages defined for self service
 * 
 */
public class MessageKeys {

  public static final String INCORRECT_OLD_PASSWORD = "INCORRECT_OLD_PASSWORD";
  public static final String EMPLOYEE_NOT_AVAILABLE = "EMPLOYEE_NOT_AVAILABLE";
  public static final String DEPENDENT_NOT_AVAILABLE = "DEPENDENT_NOT_AVAILABLE";
  public static final String ACCURAL_NOT_AVAILABLE = "ACCURAL_NOT_AVAILABLE";
  public static final String ABSENCETYPE_NOT_AVAILABLE = "ABSENCETYPE_NOT_AVAILABLE";
  public static final String ABSENCETYPE_ACCURAL_NOT_DEFINED = "ABSENCETYPE_ACCURAL_NOT_DEFINED";
  public static final String ACCURAL_NOT_DEFINED_FOR_YEAR = "ACCURAL_NOT_DEFINED_FOR_YEAR";
  public static final String SUCCESS = "SUCCESS";
  public static final String ERROR = "ERROR";
  public static final String MAPPING_EXCEPTION = "MAPPING_EXCEPTION";
  public static final String EMPLOYEE_NOT_HAVE_MANAGER_ROLE = "EMPLOYEE_NOT_HAVE_MANAGER_ROLE";
  public static final String EMPLOYEE_AND_MANAGER_NOT_MATCHING = "EMPLOYEE_AND_MANAGER_NOT_MATCHING";
  public static final String EMPLOYEE_ADDRESS_NOT_AVAILABLE = "EMPLOYEE_ADDRESS_NOT_AVAILABLE";
  public static final String EMPLOYMENT_INFORMATION_NOT_AVAILABLE = "EMPLOYMENT_INFORMATION_NOT_AVAILABLE";
  public static final String PAYROLL_PERIOD_NOT_AVAILABLE = "PAYROLL_PERIOD_NOT_AVAILABLE";
  public static final String PAYROLL_PROCESS_NOT_AVAILABLE = "PAYROLL_PROCESS_NOT_AVAILABLE";
  public static final String DATE_PARSE_EXCEPTION = "DATE_PARSE_EXCEPTION";
  public static final String BUSINESS_MISSION_CATEGORY_NOT_AVAILABLE = "BUSINESS_MISSION_CATEGORY_NOT_AVAILABLE";
  public static final String BUSINESS_MISSION_TYPE_NOT_AVAILABLE = "BUSINESS_MISSION_TYPE_NOT_AVAILABLE";
  public static final String BUSINESS_MISSION_BALANCE_NOT_AVAILABLE = "BUSINESS_MISSION_BALANCE_NOT_AVAILABLE";
  public static final String BUSINESS_MISSION_FROM_COUNTRY_NOT_AVAILABLE = "BUSINESS_MISSION_FROM_COUNTRY_NOT_AVAILABLE";
  public static final String BUSINESS_MISSION_TO_COUNTRY_NOT_AVAILABLE = "BUSINESS_MISSION_TO_COUNTRY_NOT_AVAILABLE";
  public static final String BUSINESS_MISSION_FROM_CITY_NOT_AVAILABLE = "BUSINESS_MISSION_FROM_CITY_NOT_AVAILABLE";
  public static final String BUSINESS_MISSION_TO_CITY_NOT_AVAILABLE = "BUSINESS_MISSION_TO_CITY_NOT_AVAILABLE";
  public static final String BANK_DETAILS_NOT_AVAILABLE = "BANK_DETAILS_NOT_AVAILABLE";
  public static final String BANK_NOT_AVAILABLE = "BANK_NOT_AVAILABLE";
  public static final String NOT_VALID_ACCOUNT_NUMBER = "NOT_VALID_ACCOUNT_NUMBER";
  public static final String DATE_FROM_NOT_VALID = "DATE_FROM_NOT_VALID";
  public static final String CHANGE_BANK_NOT_CREATED = "CHANGE_BANK_NOT_CREATED";
  public static final String DELEGATE_ID_NOT_EXIST = "DELEGATE_ID_NOT_EXIST";
  public static final String ATTENDANCE_NOT_CREATED = "ATTENDANCE_NOT_CREATED";
  public static final String ACTION_HISTORY_NOT_EXISTS = "ACTION_HISTORY_NOT_EXISTS";

}
